// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddMemberToTaskController from "./add_member_to_task_controller"
application.register("add-member-to-task", AddMemberToTaskController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import DashboardMarkTaskAsDoneController from "./dashboard_mark_task_as_done_controller"
application.register("dashboard-mark-task-as-done", DashboardMarkTaskAsDoneController)

import EventMessagesSubscriptionController from "./event_messages_subscription_controller"
application.register("event-messages-subscription", EventMessagesSubscriptionController)

import EventTasksController from "./event_tasks_controller"
application.register("event-tasks", EventTasksController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PosterUploadOptionsController from "./poster_upload_options_controller"
application.register("poster-upload-options", PosterUploadOptionsController)

import TabController from "./tab_controller"
application.register("tab", TabController)

import TabMembersController from "./tab_members_controller"
application.register("tab-members", TabMembersController)

import TasksController from "./tasks_controller"
application.register("tasks", TasksController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
